export enum Screen {
    Home,
    Install,
    ConfirmInstall,
    Wipe,
    AdvancedWipeSelection,
    Processing,
    Backup,
    Mount,
    Settings,
    Terminal,
    FileManager,
    Reboot,
    ChangeFileSystem,
    Magisk,
    ConfirmImageFlash,
    Odin,
}